version: "3"

services:
  db:
    image: postgres:alpine
    container_name: work_db
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app
